spring:
  profiles.active: dev
  
  secuirt:
    basic.enable: false

  datasource:
    url: jdbc:h2:mem:sbadmin2;MODE=MYSQL
    username: sa
    password:
    driverClassName: org.h2.Driver

  jpa:
    hibernate.ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  